name: Test and coverage

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
    - '!original/**'

  pull_request:
    branches: [ master ]
    paths:
    - '!original/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Code Quality
        run: poetry run black limmpca --check
      - name: Test and return coverage report
        run: poetry run pytest --cov ./limmpca --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true